### ISSUE TITLE
Filter posts to only pertinent sites

### ISSUE THREAD

**Issue by DocHuzz** [kokarn/ARK-Dev-Tracker#26]
Nubsley likes to post on a bunch of different reddit subs which really clutters the interface.  F/E: He had a ten post battle on the GTA5 forums just today/last night.  Jat has done it as well.  Could the tracker filter that mess out to only the Ark subreddit?

**Comment by kokarn** [comment]
This should actually be fixed when I find time to implement #25 (because Nubsly's actually been removed https://github.com/kokarn/ARK-Dev-Tracker/commit/1bf7d4cb5f1d03719888d5225851d858a417f91f) 

However, there are more than one subreddit which we might monitor, such as ARK One and the Survival of the Fittest. Do you have the time to build a list of the relevant ones that I could use?

**Comment by DocHuzz** [comment]
After digging through Jat, Drake, TRH, Jen, and Panda, I've only come up with four places on Reddit that they have posted any viable information.

https://www.reddit.com/r/SurviveTogether/
https://www.reddit.com/r/playark/
https://www.reddit.com/r/ARK/
https://www.reddit.com/r/ARKone/

Other than that, it's op-eds in other subreddits that have tangential information regarding the game for other sources, such as Jat offering advice to another indie gamer, or TRH explaining how certain things work in regards to servers on another page.  I wouldn't be too concerned with the SOTF reddit, as it looks more fan made than official.

**Comment by kokarn** [comment]
Wow, good work! I'll look into filtering for posts only from these subreddits

**Comment by kokarn** [comment]
This is fixed in the upcoming total rewrite. Thanks!
