### ISSUE TITLE
RSS only shows reddit and Steam

### ISSUE THREAD

**Issue by UFTimmy** [kokarn/ARK-Dev-Tracker#27]
The forum and Twitter posts do not appear in the RSS feed.

**Comment by kokarn** [comment]
Hey!

First off, the actual tracker is now developed [here](https://github.com/post-tracker/site).

The problem you are seeing with the RSS feed is twofold.
1) When we added Twitter posts, a lot of people said it was too spammy for the RSS. Posts from Twitter are therefore not included. In an upcoming version this might be an option, but for now, this will stay.
2) A couple of days ago Wildcard enabled CloudFlare DDoS protection on [survivetheark.com](https://survivetheark.com/). This makes it impossible to track the developers there. I've looked into if we could handle that with the current indexer but that's a pretty big task, especially since the whole back-end is on the finishing line for version 2. Right now there isn't much I can do except try to reach out to Wildcard about getting the indexer IP unlocked, which I'll probably look into ASAP.
